### ISSUE TITLE
examples: HTTP request example for Rye WASM console

### ISSUE THREAD

**Issue by vasilev** [refaktor/rye-website#6]
Please consider adding a HTTP request example to `Short Rye examples` / `Play in Rye console` section.

This code (feel free to rewrite it) works good in Rye WASM console available on ryelang.org:

```clojure
go does { get https://httpbin.org/get |parse-json -> "headers" -> "User-Agent" |print }
```

The snippet demonstrates the following features users can try in Rye WASM playground:
 * goroutine
 * http request
 * JSON processing 
 
 Tried to find a way to pull-request that code, but looks like `Short Rye examples` section is not available in Markdown form.
 
 BTW Thank you for the Rye language!

**Comment by refaktor** [comment]
Nice example. It works for me on native web but not in the Rye web console on ryelang.org?  I get "context deadline exceeded". I haven't yet dug deeper.

I also tried it on Chrome and there it does work. I will add it to the front page and I will try to figure out if we can make it work on FireFox too. I haven't had time to make updates to whole web console yet for quite a while. Currently main project is to equip all the base functions with unit tests and reference docs.

**Comment by refaktor** [comment]
About website. I need to redo it in hugo once so all the sources will be available. This was my first hugo project so it has a little unusual folder structure and index isn't in the content dir.

**Comment by vasilev** [comment]
> context deadline exceeded

Maybe because of timeout at

https://github.com/refaktor/rye/blob/v0.0.32/evaldo/builtins_io.go#L135

?

> FireFox

The snippet does work in my Firefox 122 on ryelang.org website. But I do confirm, sometimes where are timeout errors you mentioned. I suspected my slow Internet connection.

**Comment by refaktor** [comment]
I added it to the front page. Thank you for the example and good idea! I will try to figure out why id doesn't work on firefox ... also probably increate the hardcoded timeout you linked to.

Thank you!

**Comment by vasilev** [comment]
Thank you too!
